### ISSUE TITLE
.\mam_retrieve.exe --dsmls error : status info has been change to list instead of dictionary

### ISSUE THREAD

**Issue by taiwancycling** [taiwancycling/DevOpsUtilsTest#1]
.\mam_retrieve.exe --dsmls=\\mamstream\MAMDFS\ptstv\HVideo\2017\2017954\G201795400010001.mxf

3.6.4 |Anaconda, Inc.| (default, Jan 16 2018, 10:22:32) [MSC v.1900 64 bit (AMD64)]
10.13.210.15
\\mamstream\MAMDFS\ptstv\HVideo\2017\2017954\G201795400010001.mxf
convert path
dsmls /ptstv/HVideo/2017/2017954/G201795400010001.mxf
0
 52474569792            0            0   m      G201795400010001.mxf

G201795400010001
File G201795400010001 is migrated
Check volume status by file number ...
G201795400010001:E02986L4
Total vol in TS3500: 1127
Total unavailable vol : 19

Result:
E02986L4 : on-site, available
Traceback (most recent call last):
  File "mam_retrieve.py", line 456, in <module>
  File "mam_retrieve.py", line 366, in main
  File "mam_retrieve.py", line 118, in dsmls
AttributeError: 'list' object has no attribute 'keys'
[439272] Failed to execute script mam_retrieve

**Comment by taiwancycling** [comment]
#e084baf
![image](https://user-images.githubusercontent.com/34560799/50322183-09e28800-050f-11e9-999f-7a2a8aec633e.png)
