### ISSUE TITLE
[BUG] mam_retrieve.py :  IndexError: list index out of range

### ISSUE THREAD

**Issue by taiwancycling** [taiwancycling/DevOpsUtilsTest#7]
For news retrieve:

PS C:\Repository\DevOpsUtilsTest\Python> python .\mam_retrieve.py --fdsmrecall=dsmrecall.txt --to=/mnt/mamnas1/Retrieve/
pts/ph860129d/20190318
3.6.4 |Anaconda, Inc.| (default, Jan 16 2018, 10:22:32) [MSC v.1900 64 bit (AMD64)]
Process opt --fdsmrecall, dsmrecall.txt
Process opt --to, /mnt/mamnas1/Retrieve/pts/ph860129d/20190318
DO dsmrecall_to
DO dsmls
dsmls /news/pts/2013/04/27/201304270010022//201304270010022.MOV
0
b'   492745204            0            0   m      201304270010022.MOV\n'
File 201304270010022 is migrated
Check volume status by file number ...
201304270010022:E00041L4
Total vol in TS3500: 1131
Total unavailable vol : 8

Result:
E00041L4 : on-site, available
Total vol in TS3500: 1131
Total unavailable vol : 8
Update volume status in \\10.13.200.25\MAMDownload\tsm_off_site_vol.txt
E03168L4
E03168L4 : off-site, available

E00041L4 is on-site, available
Do dsmrecall
Total vol in TS3500: 1131
Total unavailable vol : 8
Update volume status in \\10.13.200.25\MAMDownload\tsm_off_site_vol.txt
E03168L4
E03168L4 : off-site, available

Traceback (most recent call last):
  File ".\mam_retrieve.py", line 1044, in <module>
    main(sys.argv[1:])
  File ".\mam_retrieve.py", line 951, in main
    dsmrecall_list_to(hsm, flist, target_dir)
  File ".\mam_retrieve.py", line 472, in dsmrecall_list_to
    dsmrecall_to(hsm, fpath, target_dir)
  File ".\mam_retrieve.py", line 495, in dsmrecall_to
    target_dir_win = config.MAM_STORAGE.MAMDOWNLOAD[0] + res[1]
IndexError: list index out of range

**Comment by taiwancycling** [comment]
dsmrecall.txt :
/news/pts/2013/04/27/201304270010022//201304270010022.MOV
/news/pts/2006/09/26/200609260010014//200609260010014.mov
/news/pts/2006/08/30/200608300010017//200608300010017.mov
/news/pts/2006/08/30/200608300010016//200608300010016.mov

**Comment by taiwancycling** [comment]
Fix on 55776adbd1ec3c628d24ff736656cfeb8b44589e
